apiVersion: v1
kind: Namespace
metadata:
  name: ai-toolbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-toolbox-deployment
  namespace: ai-toolbox
  labels:
    app: ai-toolbox
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ai-toolbox
  template:
    metadata:
      labels:
        app: ai-toolbox
    spec:
      containers:
      - name: ai-toolbox
        image: localhost:32000/mynginx:registry
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"